#
# Example cluster of nodes runing an example REST API service
#

VAGRANTFILE_API_VERSION = "2"

cluster_name = "SNMP"
cluster_nodes = 2
cluster_subnet = "10.0.1."

node_name = "node"
node_cpus = 1
node_mem = 512

# ENV['ANSIBLE_ROLES_PATH'] = "../ansible/roles/"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.synced_folder "../", "/shared-folder"
    config.vm.box = "geerlingguy/centos8"
    config.ssh.insert_key = false

    # workaround until pip3 install mode gets available for the ansible_local provisioner
    config.vm.provision "shell", inline: "dnf makecache && dnf -y install epel-release && dnf makecache && dnf -y install ansible"

    config.vm.provision "ansible_local" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.install = false # workaround
        #ansible.install_mode = "pip"
        #ansible.version = "2.2.1.0"
        ansible.provisioning_path = "/shared-folder/ansible"
        ansible.playbook = "snmp-provisioning.yml"
    end

    (1..cluster_nodes).each do |i|
        ip_addr = "#{cluster_subnet}#{100 + i}"
        hostname = "#{node_name}-#{i}"
        vmname = "#{cluster_name}_#{hostname}"
        config.vm.define "#{hostname}" do |cfg|
            cfg.vm.post_up_message = "SNMP stuff ready."
            cfg.vm.network "private_network", ip: "#{ip_addr}"
            cfg.vm.hostname = "#{hostname}"
            cfg.vm.provider :virtualbox do |vb|
                vb.name = "#{vmname}"
                vb.customize ["modifyvm", :id, "--memory", node_mem, "--cpus", node_cpus, "--hwvirtex", "on"]
            end # end provider
        end # end config
    end # end cluster
end

#
# EOF
#
