#
- name: Install mDNS daemon
  dnf:
    name: avahi
    state: present

- name: Name services switch for mDNS
  dnf:
    name: nss-mdns
    state: present

- name: determine interface for mDNS
  shell: route | awk '/{{ mdns_subnet }}/{ print $8 }'
  register: result

- set_fact:
    mcast_iface: "{{ result.stdout_lines | first }}"

- debug:
    msg: "Configuring mDNS on '{{ mcast_iface }}'"

- name: stop avahi daemon
  systemd:
    name: avahi-daemon
    state: stopped

- name: setup avahi daemon
  blockinfile:
    path: /etc/avahi/avahi-daemon.conf
    insertafter: "^\\[server\\]"
    block: |
      allow-interfaces={{ mcast_iface }}
      deny-interfaces=lo

- name: start avahi daemon
  systemd:
    name: avahi-daemon
    state: started
